name: alfasim-sdk-dev

includes:
  - {{ root }}/environment.devenv.yml

dependencies:
  - breathe
  - cogapp
  - doxygen
  - graphviz
  - invoke
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-datadir
  - pytest-mock
  - python
  - python-hookman
  - sphinx-click
  - toposort
  - tox
  - typing_inspect
  - pip:
    - "-r docs/requirements.txt"
