name: alfasim-sdk


dependencies:
- click
- attrs >= 19.1.0
- pytest
- pytest-cov
- pytest-datadir
- pytest-mock
- sphinx-click
- breathe

environment:
  PYTHONPATH:
    - {{ os.path.join(root) }}/src
    - {{ os.path.join(root) }}/tests/common_testing
