name: alfasim-sdk


dependencies:
- click
- attrs >= 19.1.0
- pytest
- pytest-cov
- pytest-datadir
- pytest-mock
- sphinx-click >=2.3.0
- breathe >=4.13.0

environment:
  PYTHONPATH:
    - {{ os.path.join(root) }}
