name: alfasim-sdk


dependencies:
  - attrs >= 19.1.0
  - barril
  - boltons
  - click
  - h5py
  - typing_inspect

environment:
  PATH:
    - {{ os.path.join(root, 'bin') }}

  PYTHONPATH:
    - {{ os.path.join(root, 'src') }}
    - {{ os.path.join(root, 'tests', 'common_testing') }}
