name: alfasim-sdk


dependencies:
  - click
  - attrs >= 19.1.0
  - barril
  - pytest
  - pytest-cov
  - pytest-datadir
  - pytest-mock
  - python-hookman
  - sphinx-click
  - breathe

environment:
  PYTHONPATH:
    - {{ os.path.join(root) }}/src
    - {{ os.path.join(root) }}/tests/common_testing
