GAS_PHASE = "gas"
LIQUID_PHASE = "liquid"
WATER_PHASE = "water"
SOLID_PHASE = "solid"

GAS_FIELD = "gas"
LIQUID_FIELD = "liquid"
WATER_FIELD = "water"
WATER_DROPLET_IN_LIQUID_FIELD = "water_in_liquid_droplet"
DROPLET_FIELD = "droplet"
BUBBLE_FIELD = "bubble"

GAS_LAYER = "gas"
LIQUID_LAYER = "liquid"
WATER_LAYER = "water"
