name: ALFAsim SDK

on:
  push:
    branches:
      - master
      - rb-*
    tags:
      - v*

  pull_request:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - name: Build Package
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python setup.py sdist bdist_wheel

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/